#!/bin/bash

set -eu
set -o pipefail

. debian/tests/common.sh

# Don't use grep -q here: if we do, the last grep will exit immediately,
# causing previous members of the pipeline to be killed by SIGPIPE and
# potentially exit with a nonzero status.
"${MTREE}" -c -K "${MTREE_KEYWORDS}" | "${MTREE}" -C -K "${MTREE_KEYWORDS}" |  grep md5= | grep sha1= | grep sha256= | grep gname= | grep uname= >/dev/null

# vim:set ft=sh:
