Document: mtree-netbsd
Title: Debian mtree-netbsd Manual
Author: <insert document author here>
Abstract: This manual describes what mtree-netbsd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mtree-netbsd/mtree-netbsd.sgml.gz

Format: postscript
Files: /usr/share/doc/mtree-netbsd/mtree-netbsd.ps.gz

Format: text
Files: /usr/share/doc/mtree-netbsd/mtree-netbsd.text.gz

Format: HTML
Index: /usr/share/doc/mtree-netbsd/html/index.html
Files: /usr/share/doc/mtree-netbsd/html/*.html
